// <auto-generated />
namespace CSE_DEPARTMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class teacher_nameupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teacher_nameupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202101261630183_teacher_name(update)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
