// <auto-generated />
namespace CSE_DEPARTMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _282th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_282th));
        
        string IMigrationMetadata.Id
        {
            get { return "202201281618344_282th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
