// <auto-generated />
namespace CSE_DEPARTMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class notice1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notice1));
        
        string IMigrationMetadata.Id
        {
            get { return "202201060715088_notice1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
