// <auto-generated />
namespace CSE_DEPARTMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _295th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_295th));
        
        string IMigrationMetadata.Id
        {
            get { return "202201290742341_295th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
