// <auto-generated />
namespace CSE_DEPARTMENT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class facAppli271 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(facAppli271));
        
        string IMigrationMetadata.Id
        {
            get { return "202201271622089_facAppli271"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
